nombre=input("Por favor ingresa tu nombre: ")
edad=input("Por favor ingresa tu edad: ")
nie=input("Por favor ingresa tu nie: ")
seccion=input("Por favor ingresa tu sección: ")
print("")
print("nombre: ", nombre)
print("edad: ", edad)
print("nie: ",nie)
print("seccion: ",seccion)
print("")
print("la variable nombre es de tipo", type(nombre))
print("la variable edad es de tipo", type(edad))
print("la variable nie es de tipo", type(nie))
print("la variable seccion es de tipo",type(seccion))

